version: '3'
services:
  service_springboot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - mysql
      - mongodb

  redis:
    image: "redis"
    container_name: redis
    environment:
        - TZ=Asia/Shanghai
    ports:
        - "6379:6379"
    volumes:
        - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./data/redis/:/data/
        - ./log/redis/:/var/log/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always


  mysql:
    container_name: mysql
    image: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql/:/var/lib/mysql/
      - ./data/init/:/docker-entrypoint-initdb.d/
      - ./log/mysql/:/var/log/mysql/
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always

  mongodb:
    container_name: mongodb
    image: daocloud.io/library/mongo:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "27017:27017"
    volumes:
    - /etc/localtime:/etc/localtime
    - /data/mongo/data:/data/db

    restart: always